services:
  mongo:
    image: mongo:7
    container_name: bookcompass-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: bookcompass-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
